"""add segment translated_text

Revision ID: 765aeabb8ea0
Revises: 8f551df43faf
Create Date: 2026-10-05 00:52:12.094458

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "765aeabb8ea0"
down_revision: Union[str, None] = "8f551df43faf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("segments", sa.Column("translated_text", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("segments", "translated_text")
    # ### end Alembic commands ###
